import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '../components/home/Hero'
import Navbar from '../components/home/Navbar'
import SlideShow from '../components/home/SlideShow'
import Services from '../components/home/Services'
// import ContactUs from '../components/home/ContactUs'
import Team from '../components/home/Team'
import Testimonials from '../components/home/Testimonials'
import Footer from '@/components/home/Footer'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { motion } from 'framer-motion'

const  ContactUs = dynamic(() => import('../components/home/ContactUs'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-gray-900 overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/logoBlueSmall.png" />
      </Head>
      <Navbar/>
      <Hero/>
      <SlideShow/>
      <Team/>
      <Services/> 
     {/* <ContactUs/> */}
      <Testimonials/>
      <Footer/>

      <motion.button
      className="fixed bottom-2 right-2 z-50"
           whileHover={{ scale: 1.2 }}
           whileTap={{ scale: 0.9 }}
           transition={{ type: "spring", stiffness: 400, damping: 15 }} >
           
      <Link href={`whatsapp://send?phone=+91${process.env.NEXT_PUBLIC_SUPPORT_NUMBER}`} target="_blank" className="shadow-xl">
      {/* <Link href="https://wa.me/7799444494" target="_blank" className="  shadow-xl"> */}
                   <Image
                    className=" h-20 w-auto "
                    src="/assets/whatsApp.png"
                    width={100}
                    height={100}
                    alt="ok"
                  />
                  </Link>
      </motion.button>
    </div>
  )
}
